// data.js
const studentData = [
  {
    id: 1,
    name: 'GOHIL JITENDRASINH DILIPSINH',
    course: 'ENVIRONMENT HEALTH AND SAFETY',
    batch: "3",
    enrollment_no: "CIFSE00UN3088",
    subjects: [
      { name: 'Occupational Health & Industrial Hygiene', marks: 76 },
      { name: 'Environment Safety Management', marks: 65 },
      { name: 'Psychology Ergonomics & Accident', marks: 62 },
      { name: 'Health, Safety & Environment Legislation', marks: 78 },
      { name: 'Risk Management & Permit To Work System', marks: 84 },
      { name: 'Safety In Powerplant', marks: 87 },
      { name: 'Practical 1', marks: 67 },
      { name: 'Practical 2', marks: 77 },
    ],
  },
  {
    id: 2,
    name: 'VALA AVINASH BHAGVANBHAI',
    course: 'D.F.S.E',
    batch: "MMXXII",
    enrollment_no: "CIFSE00UN7013",
    subjects: [
      { name: 'F.E.S.C', marks: 82 },
      { name: 'S.O.A', marks: 72 },
      { name: 'S.B.C', marks: 85 },
      { name: 'F.F.F.I', marks: 87 },
      { name: 'S.F.H', marks: 72 },
      { name: 'R.E.M', marks: 89 },
      { name: 'F.A.P', marks: 70 },
      { name: 'S.M', marks: 83 },
      { name: 'Practical 1', marks: 90 },
      { name: 'Practical 2', marks: 85 },
      { name: 'Practical 3', marks: 87 },
    ],
  },
  {
    id: 3,
    name: 'ADITYA DILIPBHAI DODIYA',
    course: 'FIRE MAN',
    batch: "MMXXII",
    enrollment_no: "CIFSE00UN7001",
    subjects: [
      { name: 'F.E.S.C', marks: 88 },
      { name: 'F.F.F.I', marks: 78 },
      { name: 'S.F.H', marks: 89 },
      { name: 'R.E.M', marks: 91 },
      { name: 'F.A.P', marks: 85 },
      { name: 'Safety In Powerplant', marks: 87 },
      { name: 'Practical 1', marks: 68 },
      { name: 'Practical 2', marks: 78 },
      { name: 'Practical 3', marks: 67 },
    ],
  },
  {
    id: 4,
    name: 'PARTH HARIBHAI PARMAR',
    course: 'D.F.S.E',
    batch: "MMXXII",
    enrollment_no: "CIFSE00UN7003",
    subjects: [
      { name: 'F.E.S.C', marks: 70 },
      { name: 'S.O.A', marks: 85 },
      { name: 'S.B.C', marks: 72 },
      { name: 'F.F.F.I', marks: 79 },
      { name: 'S.F.H', marks: 78 },
      { name: 'R.E.M', marks: 74 },
      { name: 'F.A.P', marks: 69 },
      { name: 'S.M', marks: 79 },
      { name: 'Practical 1', marks: 75 },
      { name: 'Practical 2', marks: 79 },
      { name: 'Practical 3', marks: 69 },
    ],
  },
  {
    id: 5,
    name: 'SATYARAJSINH DILIPSINH JADEJA',
    course: 'D.F.S.E',
    batch: "MMXXII",
    enrollment_no: "CIFSE00UN7009",
    subjects: [
      { name: 'F.E.S.C', marks: 90 },
      { name: 'S.O.A', marks: 77 },
      { name: 'S.B.C', marks: 84 },
      { name: 'F.F.F.I', marks: 91 },
      { name: 'S.F.H', marks: 73 },
      { name: 'R.E.M', marks: 78 },
      { name: 'F.A.P', marks: 84 },
      { name: 'S.M', marks: 86 },
      { name: 'Practical 1', marks: 79 },
      { name: 'Practical 2', marks: 73 },
      { name: 'Practical 3', marks: 80 },
    ],
  },
  {
    id: 6,
    name: 'DEVRAJ BHIMASHIBHAI BALIA',
    course: 'D.F.S.E',
    batch: "MMXXII",
    enrollment_no: "CIFSE00UN1012",
    subjects: [
      { name: 'F.E.S.C', marks: 78 },
      { name: 'S.O.A', marks: 72 },
      { name: 'S.B.C', marks: 69 },
      { name: 'F.F.F.I', marks: 86 },
      { name: 'S.F.H', marks: 77 },
      { name: 'R.E.M', marks: 80 },
      { name: 'F.A.P', marks: 68 },
      { name: 'S.M', marks: 78 },
      { name: 'Practical 1', marks: 90 },
      { name: 'Practical 2', marks: 79 },
      { name: 'Practical 3', marks: 72 },
    ],
  },
  {
    id: 7,
    name: 'HARPALSINH JAGMALSINH DODIYA',
    course: 'D.F.S.E',
    batch: "MMXX",
    enrollment_no: "CIFSE00UN1009",
    subjects: [
      { name: 'F.E.S.C', marks: 78 },
      { name: 'S.O.A', marks: 72 },
      { name: 'S.B.C', marks: 69 },
      { name: 'F.F.F.I', marks: 86 },
      { name: 'S.F.H', marks: 77 },
      { name: 'R.E.M', marks: 80 },
      { name: 'F.A.P', marks: 68 },
      { name: 'S.M', marks: 78 },
      { name: 'Practical 1', marks: 90 },
      { name: 'Practical 2', marks: 79 },
      { name: 'Practical 3', marks: 72 },
    ],
  },
  {
    id: 8,
    name: 'MAHIPATSINH JORUBHAI DODIYA',
    course: 'D.F.S.E',
    batch: "MMXX",
    enrollment_no: "CIFSE00UN1010",
    subjects: [
      { name: 'F.E.S.C', marks: 78 },
      { name: 'S.O.A', marks: 72 },
      { name: 'S.B.C', marks: 69 },
      { name: 'F.F.F.I', marks: 86 },
      { name: 'S.F.H', marks: 77 },
      { name: 'R.E.M', marks: 80 },
      { name: 'F.A.P', marks: 68 },
      { name: 'S.M', marks: 78 },
      { name: 'Practical 1', marks: 90 },
      { name: 'Practical 2', marks: 79 },
      { name: 'Practical 3', marks: 72 },
    ],
  },
  {
    id: 9,
    name: 'VIJAY DEVRAJBHAI JESAR',
    course: 'D.F.S.E',
    batch: "MMXXII",
    enrollment_no: "CIFSE00UN1011",
    subjects: [
      { name: 'F.E.S.C', marks: 78 },
      { name: 'S.O.A', marks: 72 },
      { name: 'S.B.C', marks: 69 },
      { name: 'F.F.F.I', marks: 86 },
      { name: 'S.F.H', marks: 77 },
      { name: 'R.E.M', marks: 80 },
      { name: 'F.A.P', marks: 68 },
      { name: 'S.M', marks: 78 },
      { name: 'Practical 1', marks: 90 },
      { name: 'Practical 2', marks: 79 },
      { name: 'Practical 3', marks: 72 },
    ],
  },
  {
    id: 10,
    name: 'JAGDISH KARABHAI SHINHORA',
    course: 'D.F.S.E',
    batch: "MMXX",
    enrollment_no: "CIFSE00UN8098",
    subjects: [
      { name: 'F.E.S.C', marks: 78 },
      { name: 'S.O.A', marks: 72 },
      { name: 'S.B.C', marks: 69 },
      { name: 'F.F.F.I', marks: 86 },
      { name: 'S.F.H', marks: 77 },
      { name: 'R.E.M', marks: 80 },
      { name: 'F.A.P', marks: 68 },
      { name: 'S.M', marks: 78 },
      { name: 'Practical 1', marks: 90 },
      { name: 'Practical 2', marks: 79 },
      { name: 'Practical 3', marks: 72 },
    ],
  },
  {
    id: 11,
    name: 'JAYPALSINH RANJITSINH MASANI',
    course: 'D.F.S.E',
    batch: "MMXX",
    enrollment_no: "CIFSE00UN7801",
    subjects: [
      { name: 'F.E.S.C', marks: 78 },
      { name: 'S.O.A', marks: 72 },
      { name: 'S.B.C', marks: 69 },
      { name: 'F.F.F.I', marks: 86 },
      { name: 'S.F.H', marks: 77 },
      { name: 'R.E.M', marks: 80 },
      { name: 'F.A.P', marks: 68 },
      { name: 'S.M', marks: 78 },
      { name: 'Practical 1', marks: 90 },
      { name: 'Practical 2', marks: 79 },
      { name: 'Practical 3', marks: 72 },
    ],
  },
  {
    id: 12,
    name: 'VIVEKBHAI LAXMANBHAI PADAYA',
    course: 'D.F.S.E',
    batch: "MMXXII",
    enrollment_no: "CIFSE00UN7834",
    subjects: [
      { name: 'F.E.S.C', marks: 78 },
      { name: 'S.O.A', marks: 72 },
      { name: 'S.B.C', marks: 69 },
      { name: 'F.F.F.I', marks: 86 },
      { name: 'S.F.H', marks: 77 },
      { name: 'R.E.M', marks: 80 },
      { name: 'F.A.P', marks: 68 },
      { name: 'S.M', marks: 78 },
      { name: 'Practical 1', marks: 90 },
      { name: 'Practical 2', marks: 79 },
      { name: 'Practical 3', marks: 72 },
    ],
  },
  {
    id: 13,
    name: 'ASHISHKUMAR NARANBHAI BARAD',
    course: 'D.F.S.E',
    batch: "MMXXIV",
    enrollment_no: "CIFSE00UN6980",
    subjects: [
      { name: 'F.E.S.C', marks: 78 },
      { name: 'S.O.A', marks: 72 },
      { name: 'S.B.C', marks: 69 },
      { name: 'F.F.F.I', marks: 86 },
      { name: 'S.F.H', marks: 77 },
      { name: 'R.E.M', marks: 80 },
      { name: 'F.A.P', marks: 68 },
      { name: 'S.M', marks: 78 },
      { name: 'Practical 1', marks: 90 },
      { name: 'Practical 2', marks: 79 },
      { name: 'Practical 3', marks: 72 },
    ],
  },
  {
    id: 14,
    name: 'SHAHIDHUSAIN SALIMMOHAMMAD THAKOR',
    course: 'D.F.S.E.',
    batch: "MMXXII",
    enrollment_no: "CIFSE00UN9007",
    subjects: [
      { name: 'F.E.S.C', marks: 78 },
      { name: 'S.O.A', marks: 72 },
      { name: 'S.B.C', marks: 69 },
      { name: 'F.F.F.I', marks: 86 },
      { name: 'S.F.H', marks: 77 },
      { name: 'R.E.M', marks: 80 },
      { name: 'F.A.P', marks: 68 },
      { name: 'S.M', marks: 78 },
      { name: 'Practical 1', marks: 90 },
      { name: 'Practical 2', marks: 79 },
      { name: 'Practical 3', marks: 72 },
    ],
  },
  {
    id: 15,
    name: 'VINOD PANCHABHAI SHIYAL',
    course: 'D.F.S.E.',
    batch: "MMXXII",
    enrollment_no: "CIFSE00UN6877",
    subjects: [
      { name: 'F.E.S.C', marks: 78 },
      { name: 'S.O.A', marks: 72 },
      { name: 'S.B.C', marks: 69 },
      { name: 'F.F.F.I', marks: 86 },
      { name: 'S.F.H', marks: 77 },
      { name: 'R.E.M', marks: 80 },
      { name: 'F.A.P', marks: 68 },
      { name: 'S.M', marks: 78 },
      { name: 'Practical 1', marks: 90 },
      { name: 'Practical 2', marks: 79 },
      { name: 'Practical 3', marks: 72 },
    ],
  },
  {
    id: 16,
    name: 'PRADEEP KUMAR OMVIR SINGH',
    course: 'D.F.S.E.',
    batch: "MMXXII",
    enrollment_no: "CIFSE00UN9032",
    subjects: [
      { name: 'F.E.S.C', marks: 76 },
      { name: 'S.O.A', marks: 70 },
      { name: 'S.B.C', marks: 68 },
      { name: 'F.F.F.I', marks: 84 },
      { name: 'S.F.H', marks: 73 },
      { name: 'R.E.M', marks: 80 },
      { name: 'F.A.P', marks: 68 },
      { name: 'S.M', marks: 79 },
      { name: 'Practical 1', marks: 90 },
      { name: 'Practical 2', marks: 79 },
      { name: 'Practical 3', marks: 72 },
    ],
  },
];

export default studentData;